{% set name = "pytest-localserver" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: 2607197f390912ab25525d129ac43c3c875049257368b3fe09b5cd03dcc526af

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<37]

requirements:
  host:
    - pip
    - python
    - setuptools >=42
    - setuptools-scm >=3.4.1
  run:
    - python
    - werkzeug >=0.10

test:
  source_files:
    - tests
  imports:
    - pytest_localserver
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests
  requires:
    - pip
    - requests
    - pytest >=2.0.0

about:
  home: https://github.com/pytest-dev/pytest-localserver
  summary: pytest plugin to test server connections locally.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    pytest-localserver is a plugin for the pytest testing framework which enables you to test server connections locally.

    Sometimes monkeypatching urllib2.urlopen() just does not cut it, for instance if you work with
    urllib2.Request, define your own openers/handlers or work with httplib. In these cases it may come in handy to
    have an HTTP server running locally which behaves just like the real thing [1]. Well, look no further!
  dev_url: https://github.com/pytest-dev/pytest-localserver
  doc_url: https://github.com/pytest-dev/pytest-localserver/blob/master/README.rst

extra:
  recipe-maintainers:
    - nicoddemus
