travis:
  secure:
    BINSTAR_TOKEN: AWPnxrvGgCjM8krEM50ooMrdBqoTxCwfOpOfrQKYjaGb28qFQ/h1SjLa8fcwlh1vy/m+0rjgoFmLBisJpAAaUNYpisZIBk7fZGd1ozxkAvr2Do62L+3UL+gDsMjLiV4NiH90hHe9nx/ZJ/1jCjqkQVjhcPrvnfSffMVUhGfSsfO1xXb3MW9LezaAekHbE7xwr7hlwYxYTeTZihfm2Th1nJZ6lybW6hiMV2ejQzromogxcniIcOye05UY5j5QuqN5liYbnxYRVgaXn8jzfCSdWNQ1jArvXz6LKAx8+ez+kaYxbacjvAEk9Wr+IBsik/CONQH4KoOm9pzF2ZvQhpUSmHsoTYybt2GOEkXr5e47ViJ4xKnntkAuyZY0yNa17ySlnlu+c6l8ClttgBcUDckUOLWRdNugdmopOOLpodAzhQbIcUiKRwlQY/0i8rY/JvWZjW6MDYFBBtyG1K2oKO4DQFZCP3u3OY0dbmjzCBfg2Yf33uwiGelFjMDYPZpUVmBcvjrJUD35Y4dgIe10pTZNIcPqyiadda5YKfttpoqUmGF9n6vMOMqPjUQLzZvuGU7f9AJzaRM/F4mWGmJGczoHYNasldAdThtIyBLJplz1Cs0nxUlcnpX5D2e73WReitMmUjpmJ4iCb38mJU0Voao2WRiMOZssJ30ondZwrb0FXeg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
