travis:
  secure:
    BINSTAR_TOKEN: IrElMKd56WglnojimcBszHpukJnGkgMWURauWdts9WtLDzP6Nfo2SSE9PO6hVZxRVHXwDVHN14m949V4IajiOcZS+8EPN15KA30CQpJPuGw60YT/GCksd7xsoMZrPxxUzB/y3MX0DEpkcODS+oOzynkEj+tww/fU3w+miXHVoN2qJdPEPN1qlip8k1HGI20tN4SobofL35nJb7wRfawhqRNOzoi8ModgJfVj6NEd534pvJUlj480CQsXH4LA0HkERPrglcANH2i8Y6DlFWZdy/fzgBKecI+MUr0+KUswNnZgM0NvT3IPodddZ8NVFKwiC3z4337ekUmrKkQ6HETmx9pNXbYSwpx2qCsuTqA1wssA/IlBrVQooG1PxPcFh0g3HzbfkZkEzE8T0cCbtS7R60J5sLK6GtxiwTzhRbYWMx+S75ipTE/A8tncfvGgzxcX7YXXUMWiQ+Pu0XZEQV0M5hEbmNJVZ8DfI2QbiWiYa1mLFidKFAQl7tu8wG4jRP+BK9fYm90xfD12MsIyIHwzLkbcYN/3Mf71ulS9k34E5izdXKeBFv61fttuJMhvfWqht1qi4jFYXPxolaArnC+o1cPNzJAMY8Dxk0PkXwyI19k5NljQHhS8n87xieALY0Lwhwvi2OZHQ43IXP4rbUbpuENjVn2HJYOd0Wq1I6x+Fdk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
