travis:
  secure:
    BINSTAR_TOKEN: OpygVgBwZbpcYrL6roZtz2bSiw0O+CpZ9MtHAgdkyMFtoFcAC4b83f2oT7KWHy5Dwr2a0aSteoEarDe9QZ2rM90hyZ0Gnxp3T47yCe82dWksusvWe8eYW3M/944dBVFvEl/AD80thU0rvUDxX9wfmyULaY9snyUBhB2OoMHKRpc2t8fyb7nRUo0lrwFLMoJrRYZkfLvjeRLg/36RScN/+mjgvoDHtQu/1uimlrTGni65Rc+JruHTOOAg+S+6wRoKKWsez7Y6QwjHRdSi9zGrDt1leQUFDTF2IB9NDBvUW53zcFQ1oqFSfkUgEntaPF4Og7pf7hN9OpApfxpDCOBGEUKYr/I1xrtH3hRa7zjZnzdmV7r/Bd7jacyvVq2//2dM3lZrZ0XRCWQmztKVpVjeLJTiLtiNlTca7PMXKFe1jC8YiHZElspD3pGXX+X8OcMTxL3EP9LYwkxRdnLdV91M9UChy0b/lPX8sTvFzuMmTgZNlodS+J20hEcdOmCaGhD4sAIk/9AQuA5IrOryLW/2pe/Cv2uc1vfFmdkT5cf8NQQJkDng7jzhmJ5Gky9SKxZ9yHXlzDw2LGrbaCvolYFKwwb+nBp4Ub3of3qgeopkHtZRm/M9CJgy0eG3l6iO4VWvD0O1fSPmLlFVZXdi0Vm6x9XTRmExpYDPhmM0NfXf4XA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
